baseURL: 'http://roboweb.app/'
languageCode: 'en-us'
title: 'Roboweb'
theme: "ananke"
# see https://gohugo.io/templates/menu-templates/#section-menu-for-lazy-bloggers
sectionPagesMenu: main
menu:
  main:
  # Add an extra menu icon to handle login.
  - identifier: login
    name: Login
    url: https://ui.roboweb.app
    weight: -110

params:
  env: production
  description: "An AI Assistant for Exploratory Programmingßßß"

# https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032/15
# Needed to render html shortcodes used for videos
markup:
  goldmark:
    renderer:
      unsafe: true