apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: roboweb
resources:
- statefulset.yaml
images:
- name: notebook
  newName: us-west1-docker.pkg.dev/roboweb-images/roboweb-images/kubeflow/jupyterlab
  newTag: latest
